<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-25T08:12:50 IST" name="Default suite" finished-at="2022-06-25T08:13:12 IST" duration-ms="22019">
    <groups>
    </groups>
    <test started-at="2022-06-25T08:12:50 IST" name="Default test" finished-at="2022-06-25T08:13:12 IST" duration-ms="22019">
      <class name="_23POMWithPFMAndTestNG._4LoginWithGenrics">
        <test-method is-config="true" signature="OpenApplication()[pri:0, instance:_23POMWithPFMAndTestNG._4LoginWithGenrics@123ef382]" started-at="2022-06-25T08:12:50 IST" name="OpenApplication" finished-at="2022-06-25T08:12:58 IST" duration-ms="7782" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenApplication -->
        <test-method signature="registration()[pri:1, instance:_23POMWithPFMAndTestNG._4LoginWithGenrics@123ef382]" started-at="2022-06-25T08:12:58 IST" name="registration" finished-at="2022-06-25T08:13:01 IST" duration-ms="2948" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Your Account Has Been Created!] but found [Register Account]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Your Account Has Been Created!] but found [Register Account]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at _23POMWithPFMAndTestNG._4LoginWithGenrics.registration(_4LoginWithGenrics.java:92)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registration -->
        <test-method is-config="true" signature="CloseApplication()[pri:0, instance:_23POMWithPFMAndTestNG._4LoginWithGenrics@123ef382]" started-at="2022-06-25T08:13:01 IST" name="CloseApplication" finished-at="2022-06-25T08:13:01 IST" duration-ms="128" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseApplication -->
        <test-method is-config="true" signature="OpenApplication()[pri:0, instance:_23POMWithPFMAndTestNG._4LoginWithGenrics@123ef382]" started-at="2022-06-25T08:13:01 IST" name="OpenApplication" finished-at="2022-06-25T08:13:08 IST" duration-ms="6843" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenApplication -->
        <test-method signature="Login1()[pri:2, instance:_23POMWithPFMAndTestNG._4LoginWithGenrics@123ef382]" started-at="2022-06-25T08:13:08 IST" name="Login1" finished-at="2022-06-25T08:13:12 IST" duration-ms="4184" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login1 -->
        <test-method is-config="true" signature="CloseApplication()[pri:0, instance:_23POMWithPFMAndTestNG._4LoginWithGenrics@123ef382]" started-at="2022-06-25T08:13:12 IST" name="CloseApplication" finished-at="2022-06-25T08:13:12 IST" duration-ms="102" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseApplication -->
      </class> <!-- _23POMWithPFMAndTestNG._4LoginWithGenrics -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
