<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-88V4A8K" failures="2" tests="13" name="_22testngDummyCode.LearningtestNg" time="0.042" errors="0" timestamp="2022-06-25T07:25:52 IST" skipped="0">
  <testcase classname="_22testngDummyCode.LearningtestNg" name="registration" time="0.009">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at _22testngDummyCode.LearningtestNg.registration(LearningtestNg.java:67)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- registration -->
  <system-out/>
  <testcase classname="_22testngDummyCode.LearningtestNg" name="login" time="0.004"/>
  <system-out/>
  <testcase classname="_22testngDummyCode.LearningtestNg" name="loginWithInvalidCredentails" time="0.007">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at _22testngDummyCode.LearningtestNg.loginWithInvalidCredentails(LearningtestNg.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- loginWithInvalidCredentails -->
  <system-out/>
  <testcase classname="_22testngDummyCode.LearningtestNg" name="ContactUs" time="0.002"/>
  <system-out/>
  <testcase classname="_22testngDummyCode.LearningtestNg" name="ContactUs" time="0.003"/>
  <system-out/>
  <testcase classname="_22testngDummyCode.LearningtestNg" name="ContactUs" time="0.002"/>
  <system-out/>
  <testcase classname="_22testngDummyCode.LearningtestNg" name="ContactUs" time="0.003"/>
  <system-out/>
  <testcase classname="_22testngDummyCode.LearningtestNg" name="ContactUs" time="0.001"/>
  <system-out/>
  <testcase classname="_22testngDummyCode.LearningtestNg" name="ContactUs" time="0.002"/>
  <system-out/>
  <testcase classname="_22testngDummyCode.LearningtestNg" name="ContactUs" time="0.001"/>
  <system-out/>
  <testcase classname="_22testngDummyCode.LearningtestNg" name="ContactUs" time="0.004"/>
  <system-out/>
  <testcase classname="_22testngDummyCode.LearningtestNg" name="ContactUs" time="0.002"/>
  <system-out/>
  <testcase classname="_22testngDummyCode.LearningtestNg" name="ContactUs" time="0.002"/>
  <system-out/>
</testsuite> <!-- _22testngDummyCode.LearningtestNg -->
